### PR TITLE
first version of comm update

### PR DESCRIPTION
**Pull request by jcolomb**
PR please add your 2 cents

### CODE REVIEW

**Comment by etothczifra** [comment]
## Governance and tasks distribution
Text suggestion: 

Make your voice heard! One of our key priorities for 2020 is to renew our Steering Committee. If you are interested to join us, please contact us on the Slack #steering channel. 

##Meet us at the Open Science Barcamp!

It's only a couple of days to go until one of the most exciting Open Science events of the year. We proposed two sessions for the[ Open Science Barcamp](https://www.open-science-conference.eu/barcamp/), the innovative day 0 of the more formal Berlin Open Science Conference. You can find more details here:  https://etherpad.wikimedia.org/p/oscibar2020 Come and explore what is there for you in the MOOC or how you can integrate your own perspectives on Open Science!

You can follow the event on twitter via the #oscibar hashtag and listen to last year's highlights on the Open Science Radio : http://www.openscienceradio.org/. 

These are my suggestions for now. For next month, I can go back to Bastian and check on the progress with his Citizen Science grant. The proposals for the Barcamp look great to me, thanks a lot, Jo and Julien!

**Comment by jcolomb** [comment]
@dannycolin do you know why it was not deployed? can we see how it will look like when deployed? (due to the embed form, I would like to see it before it goes live)

**Comment by dannycolin** [comment]
> @dannycolin do you know why it was not deployed? can we see how it will look like when deployed? (due to the embed form, I would like to see it before it goes live)

You need someone to review a PR before you can merge it. And, yes, I'll look at it ;).

**Review by dannycolin — APPROVED** [review]
I've tested it locally and sent a screenshot to @jcolomb on Slack. It looks good to me so I'll approve the review. If you made some changes and need a new review don't hesitate to ping me here or on Slack.

**Comment by tosteiner** [comment]
@jcolomb don't know if you've been in touch with others regarding the planned publication date of our announcement? 

Any news on that from anybody (also asking all of us here more generally 😉 )?

**Pull request merged**
