### PR TITLE
Update open-research-software-and-open-source.md

### PR DESCRIPTION
**Pull request by pablobernabeu**
Removed my own blog post on data dashboards, as it better fits the Open Data module, and added authors to some entries.

### CODE REVIEW

**Review by pablobernabeu — COMMENTED** [review]
Corrected a parenthesis

**Comment by mroyme** [comment]
@pablobernabeu For the sake of maintaining uniformity, wouldn't it be better to use the comma convention like the other entries instead of the parentheses?

**Review by pablobernabeu — COMMENTED** [review]
Minor format corrections of references

**Comment by pablobernabeu** [comment]
Thank you, @madhurjyaroy. I've corrected that now.

**Review by mroyme — APPROVED** [review]

**Comment by mroyme** [comment]
Thanks @pablobernabeu 👍

**Pull request merged**
